import { Link, usePage } from '@inertiajs/react';
import PublicLayout from '@/Layouts/PublicLayout';

const formatCurrency = (amount) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(amount);

export default function OrderSuccess({ order }) {
    const bank = usePage().props.settings?.branding ?? {};
    const isTransfer = order.payment_method === 'transfer';
    const hasBankInfo = Boolean(bank.store_bank_number);
    return <PublicLayout title="Pesanan Berhasil Dibuat"><section className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:py-16"><div className="rounded-3xl border border-amber-900/10 bg-white p-6 text-center shadow-sm sm:p-10"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-100 text-2xl text-emerald-800">✓</div><p className="mt-5 text-xs font-bold uppercase tracking-[0.22em] text-amber-700">Pesanan berhasil dibuat</p><h1 className="mt-3 break-words font-serif text-4xl font-bold text-emerald-950">Terima kasih, {order.customer_name}</h1><p className="mx-auto mt-4 max-w-lg text-sm leading-7 text-stone-600">Pesanan Anda telah dicatat. {isTransfer ? 'Silakan transfer sesuai total pesanan agar pesanan Anda segera dikonfirmasi.' : 'Silakan lakukan pembayaran saat pengambilan pesanan.'}</p><div className="mt-7 rounded-2xl bg-amber-50 p-5"><p className="text-xs font-bold uppercase tracking-[0.18em] text-amber-800">Nomor pesanan</p><p className="mt-2 break-all font-mono text-lg font-bold text-emerald-950">{order.invoice_number}</p><p className="mt-3 text-sm font-semibold text-amber-900">Menunggu pembayaran · {isTransfer ? 'Transfer Bank' : 'Bayar saat pengambilan'}</p>{isTransfer && hasBankInfo ? <p className="mt-2 text-sm leading-6 text-stone-600">Transfer ke {bank.store_bank_name ? `${bank.store_bank_name} ` : ''}{bank.store_bank_number}{bank.store_bank_holder ? ` a.n. ${bank.store_bank_holder}` : ''}</p> : null}</div><div className="mt-8 text-left"><h2 className="font-serif text-2xl font-bold text-emerald-950">Ringkasan</h2><div className="mt-4 space-y-3">{order.items.map((item, index) => <div key={index} className="flex justify-between gap-4 text-sm"><span className="text-stone-700">{item.name} × {item.quantity}</span><span className="font-semibold text-emerald-900">{formatCurrency(item.subtotal)}</span></div>)}</div><div className="mt-5 space-y-2 border-t border-amber-900/10 pt-4 text-sm"><div className="flex justify-between text-stone-600"><span>Subtotal</span><span>{formatCurrency(order.subtotal)}</span></div><div className="flex justify-between text-stone-600"><span>PPN 11%</span><span>{formatCurrency(order.tax)}</span></div><div className="flex justify-between font-serif text-xl font-bold text-emerald-950"><span>Total</span><span>{formatCurrency(order.total)}</span></div></div></div><Link href={route('store.home')} className="mt-9 inline-flex rounded-xl bg-emerald-800 px-5 py-3 text-sm font-bold text-white hover:bg-emerald-700">Kembali ke beranda</Link></div></section></PublicLayout>;
}
